language: java
jdk: oraclejdk8

env:
  global:
    secure: "QQt1iqe7lQbDECfw1Gr9tL0F0yrjSFSTMWv9h7V0Qlg/2i0/Qp5TcbI/y86MsDPcy7Po9QRymrPz1M9C+KI85/gMrebimjIDXL9Zc8r21XhiXmrYZ0eztoGTTDZUHLfsfoUOS4chchOkGj5SGBqEIHMtpkg2MMyBETmR29IljdfGAR5GtfEle0HKhSS4zNmwVQXwEpGJVslFE2UBhpXM72MoykMW5wJ6imUS1k5WCjGCadCmCeNKUuNypgipgCz2KPgsqqBXEmsdR8TpigZudnInjP2NQSn9/FpLU6CWVVnWWIVMYlKu/wbHCa+4RJC0ERww+Ex85wVMQoU6cgnfIp2YDPvfq956GXoQjU2QmUJ5iJfL96T4qAfOfnJZ0YZ9WO0DoV8X4x4Ge7wf76j2AM2klOpKfJrJl181vhxVkHtdcxkpezaXEvP305FHfvPx2llhjBnVF1mJdxoL0qW6YE2i9IM+AG7a1QT1CrJoz16tH6ukXlCSuAQE7Blg6AmcFzhifIXZ8DsKVL9kOmDtjZHYHjUybTLEDpFTuypUy0b0TiB9GBw6toIh5RakWFHe8Clqs/M37r7muUd/2kC56qP8FkIk1JN2If06Zho4pR14mVkIK7NjPg3Z3nZeKphnlLig9b0rbXrNmAS3IH6R9RUYvI6wazjKAN7Aq0/8z3A="


jobs:
  allow_failures:
    - stage: test
  include:
    - stage: build
      script:
        - mvn clean install -B -V -DskipTests
        - mkdir deploy
        - cp -v "target/$(ls target | grep jar-with-dependencies.jar)" deploy/sh.jar
        - mvn javadoc:javadoc
        - .util/pages.sh
      deploy:
        provider: releases
        api_key:
          secure: "QQt1iqe7lQbDECfw1Gr9tL0F0yrjSFSTMWv9h7V0Qlg/2i0/Qp5TcbI/y86MsDPcy7Po9QRymrPz1M9C+KI85/gMrebimjIDXL9Zc8r21XhiXmrYZ0eztoGTTDZUHLfsfoUOS4chchOkGj5SGBqEIHMtpkg2MMyBETmR29IljdfGAR5GtfEle0HKhSS4zNmwVQXwEpGJVslFE2UBhpXM72MoykMW5wJ6imUS1k5WCjGCadCmCeNKUuNypgipgCz2KPgsqqBXEmsdR8TpigZudnInjP2NQSn9/FpLU6CWVVnWWIVMYlKu/wbHCa+4RJC0ERww+Ex85wVMQoU6cgnfIp2YDPvfq956GXoQjU2QmUJ5iJfL96T4qAfOfnJZ0YZ9WO0DoV8X4x4Ge7wf76j2AM2klOpKfJrJl181vhxVkHtdcxkpezaXEvP305FHfvPx2llhjBnVF1mJdxoL0qW6YE2i9IM+AG7a1QT1CrJoz16tH6ukXlCSuAQE7Blg6AmcFzhifIXZ8DsKVL9kOmDtjZHYHjUybTLEDpFTuypUy0b0TiB9GBw6toIh5RakWFHe8Clqs/M37r7muUd/2kC56qP8FkIk1JN2If06Zho4pR14mVkIK7NjPg3Z3nZeKphnlLig9b0rbXrNmAS3IH6R9RUYvI6wazjKAN7Aq0/8z3A="
        file_glob: true
        file: deploy/sh.jar
        skip_cleanup: true
        on:
          repo: lfuelling/sh
          tags: true

    - stage: test
      script:
        - mvn clean install -B -V